### ISSUE TITLE
Installation via AltStore Failed

### ISSUE THREAD

**Issue by sjfreed21** [IdreesInc/Apple-Watch-Poketch#2]
Invalid value of WKCompanionAppBundleIdentifier key in Info.plist
![IMG_4507](https://user-images.githubusercontent.com/54907915/142673849-7e9016e4-0301-4af6-b790-c327910b23c3.PNG)

**Comment by IdreesInc** [comment]
Unfortunately, I am not sure how to sideload to an Apple Watch without Xcode and I can only make the ipa bundles available. Looks like the Apple Watch app that is bundled with the ipa has an autogenerated bundle identifier which I can't change. You can instead use the TestFlight link posted here: https://testflight.apple.com/join/jd1cqyip

**Comment by sjfreed21** [comment]
Thanks for the TestFlight link, that works great! Hope I didn't come off too harsh in the original post!

**Comment by IdreesInc** [comment]
Not at all, glad it worked!

**Comment by farzadso** [comment]
I've got it installed on my phone too, but don't know what to do on my apple watch. Is it a face?
