### ISSUE TITLE
pressedAnimationFrame is redeclarared in the Stopwatch

### ISSUE THREAD

**Issue by anthonyhuang07** [IdreesInc/Apple-Watch-Poketch#8]
fixes when the line is removed, and I don't notice any abnormalities. the app won't build without removing it

<img width="356" alt="image" src="https://user-images.githubusercontent.com/90001131/201941175-8441ac63-d8b5-48d3-b071-deac5147cd9d.png">

**Comment by IdreesInc** [comment]
I think this might be an old branch, I fixed this issue a few months back. Are you still seeing it when you pull from main?
